### ISSUE TITLE
Hello-blockchain API returns 401

### ISSUE THREAD

**Issue by robinth462** [Azure-Samples/blockchain#134]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Install the hello-blockchain application.
> Access the URL, create and execute contracts. - Works fine
> App service Authentication is switched off. 
> When using the API, I can not return any values at all, the error I am getting is 401.
> I repeated the steps above with the App service Authentication switched on. - Still error 401

### Any log messages given by the failure
> 401

### Expected/desired behavior
> With the App Service Authentication switched off, when executing 'https://cmblockchain-tnqc4z-api.azurewebsites.net/api/v1/users/1' I should get the user details. 

### OS and Version?
> Windows 7, Chrome

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ali92hm** [comment]
This is the expected behavior. We do not rely on the App service authentication for Workbench and authentication cannot be turned off.

If you are trying to use Workbench's API problematically please take a look at this [Q&A](https://github.com/Azure-Samples/blockchain/tree/master/blockchain-workbench/faq#q-im-trying-to-access-workbenchs-api-programmatically-using-a-service-principal-but-i-get-errors-when-calling-the-api)
