### ISSUE TITLE
Rest API [Contract Action] succeeds but nothings happens on workbench UI

### ISSUE THREAD

**Issue by mesgar** [Azure-Samples/blockchain#214]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Trying to take Ingest Telemetry action from REST API for contract id 6.
![image](https://user-images.githubusercontent.com/10726024/69438738-ec561800-0d88-11ea-8695-b0202e3dbf25.png)
![image](https://user-images.githubusercontent.com/10726024/69439118-a51c5700-0d89-11ea-97d1-18609a8e626b.png)

Both Get and Post calls are successful with HTTP code 200.
![image](https://user-images.githubusercontent.com/10726024/69439028-7dc58a00-0d89-11ea-9320-a3e4b3b0d75b.png)
![image](https://user-images.githubusercontent.com/10726024/69439065-8f0e9680-0d89-11ea-844e-2d928ef4fb9b.png)

But nothing happens on the screen or database.
![image](https://user-images.githubusercontent.com/10726024/69439327-0f34fc00-0d8a-11ea-8aef-0e54c6b8f157.png)

![image](https://user-images.githubusercontent.com/10726024/69439183-c8df9d00-0d89-11ea-8ed2-b6f2601e7259.png)

### Expected/desired behavior
>
Shouldn't it displays "IngestTelemetry" action and telemetry data?

**Comment by asergaz** [comment]
For reference issue started here: https://social.msdn.microsoft.com/Forums/en-US/393902a3-b6ec-4fc5-bf0d-1cfa3ceb535b/abw-restapi-doesnt-work-on-device-telemetry?forum=azureblockchain

**Comment by ramyapradhan** [comment]
Hello mesgar,

Please allow me to point out a two things because of which you are not able to see 'Ingest Telemetry'.

First is that 'Ingest Telemetry' can only be called by the AAD user who has been assigned the 'Device' role.  Please log in to your Workbench instance as the AAD user who has been assigned the 'Device' role.  If the next available action is 'Ingest Telemetry', then that user will be able to see it on their dashboard.  An entry in the database will show up when this action is taken and is successful.

Second is that the action 'Transfer Responsibility' is completely different from 'Ingest Telemetry' and calling one will not cause the other one to also be called.  I think this confusion may have stemmed from the fact that these two actions are shown as available when the state is in 'In Transit'; as illustrated in the state transition diagram [here](https://github.com/Azure-Samples/blockchain/tree/master/blockchain-workbench/application-and-smart-contract-samples/refrigerated-transportation).  Please note the distinction in who can take these actions (shown in green), in that 'Transfer Responsibility' can be taken by the AAD user in the IntiatingCounterParty or the CounterParty role and 'Ingest Telemetry' can only be taken by the AAD user in the Device role.  If the roles do not match, then that action will not be shown by Workbench UI nor will the action be recorded in the database.

I hope this helps.

**Comment by ramyapradhan** [comment]
Hello @mesgar, 

I am writing to inform you that I will be closing this issue since it has been open for more than 30 days.  Please feel free to re-open it if you need more information.

Thanks,
Ramya
