### ISSUE TITLE
Does the workbench base class no longer needed? 

### ISSUE THREAD

**Issue by xtianus79** [Azure-Samples/blockchain#225]
WorkbenchBase.sol - This file contains the Workbench base class and the event definitions.

<<< is this no longer needed?

**Comment by ramyapradhan** [comment]
Hi @xtianus79, yes, you now no longer require WorkbenchBase.sol.  This has been the case since Workbench 1.6.0 release.  Please find the [Workbench 1.6.0 release blog here](https://azure.microsoft.com/en-us/blog/streamlined-development-experience-with-azure-blockchain-workbench-1-6-0/). 
Thanks,
Ramya
