### ISSUE TITLE
ProcessEventsWithAzureFunctions missing code in sample function 

### ISSUE THREAD

**Issue by HowardEdidin** [Azure-Samples/blockchain#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
ProcessEventsWithAzureFunctions function app code missing for case statements
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mmercuri** [comment]
The function is a shell which shows you how to capture the incoming message so that you can execute your own logic.  This was made more explicit in the text. 

See the [CosmosDB sample](https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/data-reporting-samples/CosmosDB/readme.md) as an example of this being used with logic to send a message to CosmosDB.
